plugins {
	alias libs.plugins.android.library
	id 'maven-publish'
}

android {
	namespace 'cz.adaptech.tesseract4android'
	compileSdk 35

	defaultConfig {
		minSdk 21
		targetSdk 35

		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		missingDimensionStrategy 'parallelization', 'standard'
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
		debug {
			externalNativeBuild {
				cmake {
					// Force building release version of native libraries even in debug variant.
					// This is for projects that has direct dependency on this library,
					// but doesn't really want its debug version, which is very slow.
					// Note that this only affects native code.
					arguments += "-DCMAKE_BUILD_TYPE=Release"
				}
			}
		}
	}
	flavorDimensions = ["parallelization"]
	productFlavors {
		standard {
		}
		openmp {

		}
	}
	publishing {
		singleVariant("standardRelease") {
			withSourcesJar()
			withJavadocJar()
		}
		singleVariant("openmpRelease") {
			withSourcesJar()
			withJavadocJar()
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
	buildFeatures {
		buildConfig true
	}
}

dependencies {
	// Intentionally use old version of annotation library which doesn't depend on kotlin-stdlib
	// to not unnecessarily complicate client projects due to potential duplicate class build errors
	// caused by https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target
	//noinspection GradleDependency
	standardImplementation project(":internals")
	openmpImplementation project(":internals")

	implementation libs.androidx.annotation

	testImplementation libs.junit
	androidTestImplementation libs.androidx.test.runner
	androidTestImplementation libs.androidx.test.rules
	androidTestImplementation libs.androidx.test.ext.junit
	androidTestImplementation libs.androidx.test.espresso.core
}

afterEvaluate {
	publishing {
		publications {
			standard(MavenPublication) {
				from components.findByName('standardRelease')

				groupId 'cz.adaptech'
				artifactId 'tesseract4android'
				version rootProject.ext.tesseract4AndroidVersion
			}
			openmp(MavenPublication) {
				from components.findByName('openmpRelease')

				groupId 'cz.adaptech'
				artifactId 'tesseract4android-openmp'
				version rootProject.ext.tesseract4AndroidVersion
			}
		}
	}
}
